### PR TITLE
MNT: Update to pylint 1.8.1 and re-rendered with conda-smithy 2.4.4

### PR DESCRIPTION
**Pull request by timleslie**

### CODE REVIEW

**Comment by jakirkham** [comment]
Thanks @timleslie. Any interest in helping maintain?

**Comment by timleslie** [comment]
@jakirkham Happy to help out where possible, sure!

**Comment by jakirkham** [comment]
In that case, please feel free to add your GitHub handle to the `recipe-maintainers` list in `meta.yaml`.

**Comment by jakirkham** [comment]
Also we may want to switch this over to a [`noarch: python` package]( https://conda-forge.org/docs/meta.html#building-noarch-packages ).

**Comment by timleslie** [comment]
Have added myself to the maintainers. I don't think we can go to noarch yet, as we have some python 2.7 specific dependancies (backports.functools_lru_cache, configparser, singledispatch).

**Comment by jakirkham** [comment]
Thanks. Good point.

**Comment by jakirkham** [comment]
Thanks @timleslie. Should get an invite to join conda-forge momentarily, which will provide merge permissions on this feedstock.

**Pull request merged**
