### PR TITLE
Increase min astroid version

### PR DESCRIPTION
**Pull request by wshanks**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

This matches upstream

### CODE REVIEW

**Comment by wshanks** [comment]
@conda-forge-admin, please rerender

**Comment by bollwyvl** [comment]
Given the number of times this has snuck through, perhaps we should
- move the astroid version to a Jinja variable
- use it in the pin in run and
-  force installing that in the test environment

**Comment by bollwyvl** [comment]
Thanks!

**Comment by wshanks** [comment]
Nice! I like pinning the astroid version. Now `pip check` will fail if we don't update the min version.

**Comment by bollwyvl** [comment]
Cool.  I guess we could add some test thing that compared, but this seems a
bit more direct: pip check is about the most robust thing we have.

**Pull request merged**
