### PR TITLE
Update to 2.7.2

### PR DESCRIPTION
**Pull request by wshanks**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

This is the same as #52 to test if the CI failure is reproducible.

### CODE REVIEW

**Comment by jakirkham** [comment]
Thanks for working on this 😄

Looks like 2.7.2 was tagged recently. Could we update to that?

Also please make sure the requirements in the recipe match [upstream's]( https://github.com/PyCQA/pylint/blob/3dfecb0b269f3594b2e211032fbfa54ee80f6aaa/pylint/__pkginfo__.py#L41-L46 )

**Comment by wshanks** [comment]
Good catch about the dependencies. The necessary version of astroid changed. I updated the PR to update to 2.7.2 and fix the astroid version. I am surprised the bot hadn't opened a new PR for 2.7.2.

**Comment by jakirkham** [comment]
The bot runs roughly every 6hrs on a cron job. Also the bot regulates how many PRs are opened at a time to avoid overloading CI. So it's not too surprising (particularly if it was fairly recent).

**Review by jakirkham — APPROVED** [review]

**Comment by jakirkham** [comment]
Thanks again for working on this! 😄

**Pull request merged**
