### PR TITLE
pylint 2.8.2, pip check, maintainers, noarch

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Notes
- includes #59 (thanks @wshanks :tada:)
- makes `noarch: python`
- adds `pip check` (i'm getting issues downstream)
- updates `astroid` dep
- update some urls
- adds self as maintainer :wave:

### CODE REVIEW

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
@conda-forge/pylint ready for review! @wshanks chime in if you'd like to help maintain, and i can add you... or merge this PR into yours and DIY!

**Comment by wshanks** [comment]
Thanks, @bollwyvl. You can add me. I will close #59.

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
@conda-forge/pylint back to ready for review!

**Review by marcelotrevisani — APPROVED** [review]

**Pull request merged**
