### PR TITLE
MNT: Re-rendered with conda-smithy 2.0.0

### PR DESCRIPTION
**Pull request by goanpeca**

### CODE REVIEW

**Comment by dopplershift** [comment]
Looks like isort needs python 3.6 packages first.

**Comment by goanpeca** [comment]
t

**Comment by jakirkham** [comment]
Merged that one. Now we wait.

**Comment by goanpeca** [comment]
@jakirkham https://travis-ci.org/conda-forge/pylint-feedstock/jobs/193224828 ?

**Comment by jakirkham** [comment]
Would have guessed this would run after `isort` when I restarted it. Guess not. 😕 Feel free to ping and/or restart this one after `isort`'s OS X builds are out.

ref: https://travis-ci.org/conda-forge/isort-feedstock/builds/193473769

**Comment by goanpeca** [comment]
@jakirkham ready :-)

**Comment by jakirkham** [comment]
Thanks @goanpeca .

**Pull request merged**
